services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"  # Porta per AMQP
    - "15672:15672"  # Porta per l'interfaccia di gestione
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

  producer:
    build: ./producer
    container_name: producer
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_IP=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  consumer:
    build: ./consumer
    container_name: consumer
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_IP=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
volumes:
    rabbitmq_data: